version: '3.8'
services:
  user-service:
    build: ./user-service
    ports:
      - "8085:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/userservice
    depends_on:
      - mongo

  news-service:
    build: ./news-service
    ports:
      - "8087:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/userservice
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9093
    depends_on:
      - kafka
      - mongo
      - user-service

  ai-service:
    build: ./ai-service
    ports:
      - "8088:8080"
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - kafka

  email-service:
    build: ./email-service
    ports:
      - "8086:8080"
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - kafka

  kafka:
    image: confluentinc/cp-kafka:6.2.0
    ports:
      - "9093:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    ports:
      - "2182:2181"

  mongo:
    image: mongo:4.4.6
    ports:
      - "27017:27017"

networks:
  default:
    driver: bridge